### ISSUE TITLE
vim-youcompleteme-git 上游更新，打包需修改

### ISSUE THREAD

**Issue by Universebenzene** [archlinuxcn/repo#1487]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* vim-youcompleteme-git

----

请在此补充说明。
ycm上游又更新，源里的r2610打出来不能用了，[AUR](https://aur.archlinux.org/cgit/aur.git/commit/?h=vim-youcompleteme-git&id=0fe4c6fae8caa3cbd2a91e1dff4e0694d851c528)已跟进上游，目前看来打出来能用，咱这也跟进下罢

**Comment by dctxmei** [comment]
已跟進：https://github.com/archlinuxcn/repo/commit/d75c3122f7fa72c37c3133a06880769b6b9b5252

**Comment by poscat0x04** [comment]
在 update_on 里加入 aur 比较好

**Comment by dctxmei** [comment]
> 在 update_on 里加入 aur 比较好

`update_on` 裡的 `github` 和 `aur` 可以直接混用的嘛？

**Comment by poscat0x04** [comment]
update_on 是只要有一个触发了就会重新打包
同时可以在 pre_build 里面同步 AUR 的 PKGBUILD

**Comment by dctxmei** [comment]
> update_on 是只要有一个触发了就会重新打包
> 同时可以在 pre_build 里面同步 AUR 的 PKGBUILD

我注意 repo 裡的 `-git` 更多是類似如下情況：
```yaml
pre_build: vcs_update

post_build: git_pkgbuild_commit

update_on:
    - github: Valloric/YouCompleteMe
    - alias: clang

maintainers:
    - github: dctxmei
```
而混用的情況倒是比較少見，我參考了 [vokoscreen-git](https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/vokoscreen-git/lilac.yaml)，不知如下是否可行：
```yaml
pre_build: aur_pre_build

post_build: aur_post_build

update_on:
    - aur: vim-youcompleteme-git
    - github: Valloric/YouCompleteMe
    - alias: clang

maintainers:
    - github: dctxmei
```
