### ISSUE TITLE
hplip-plugin过期了

### ISSUE THREAD

**Issue by hubutui** [archlinuxcn/repo#1520]
### 问题类型 / Type of issues

* 过期软件包 / out-of-date packages

### 受影响的软件包 / Affected packages

*  hplip-plugin

----

是不是考虑一下让 lilac 自动打包更新？不知道这样写行不行，`hplip-plugin` 与 `hplip` 版本应该是保持一致的？直接让 lilac 去查官方源里的 `hplip` 的版本，然后更新吧。`lilac.yaml`:
```
maintainers:
  - github: colinkeenan
build_prefix: extra-x86_64
update_on:
  - archpkg: hplip
    strip_release: true
```
以及 `lilac.py`:
```python
#!/usr/bin/env python3

from lilaclib import *

def pre_build():
  update_pkgver_and_pkgrel(_G.newver.lstrip('v'))

def post_build():
  git_add_files('PKGBUILD')
  git_commit()
# vim:set ts=2 sw=2 et:
```
