### ISSUE TITLE
clash-meta无法使用内置的iptables模块配置透明代理

### ISSUE THREAD

**Issue by handsomexdd1024** [archlinuxcn/repo#3099]
### 问题类型 / Type of issues

* 打包错误 / packaging error

### 受影响的软件包 / Affected packages

* clash-meta

----

clash-meta软件包在使用安装附带的systemd service文件时，无法通过自带的iptables管理模块开启透明代理。报错信息如下：
`can't open lock file /run/xtables.lock: Permission denied`
/run/xtables.lock的权限为-rw------- root root，似乎表明以clash-meta用户身份无法修改iptables.

（但clash-meta.service里面又有`CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_RAW CAP_NET_BIND_SERVICE`，就很迷……）
/etc/clash-meta/config.yaml中相关配置如下：
```
tproxy-port: 7893          #本地Linux Tproxy代理端口
iptables:
  enable: true
  inbound-interface: lo
```
