### ISSUE TITLE
lilac.yaml 配置文件

### ISSUE THREAD

**Issue by lilydjwg** [archlinuxcn/repo#883]
### 问题类型 / Type of issues
* 其它 / other
----

将一些数据形式的字段从 lilac.py 独立出来，方便编写。代码部分还是放在 lilac.py 中。

这些字段包括：

* [x] update_on
* [x] depends
* [x] time_limit_hours
* [x] pre_build / post_build / post_build_always (指定函数名)
* [x] maintainers
* [x] output_packages (取代 package.list)

大家觉得如何呢？

一个 lilac.yaml 大概会是这样子：

```yaml
update_on:
  - aur
  - github: username/repo
    use_latest_release: true
depends:
  - this-pkg
  - a-split-pkg: some-pkg-name
```

另外，lilac.py 需要能够访问这些数据么？

相关事务：

* [x] 生成 lilac.yaml 文档
* [x] 在 pre-commit 中检查 lilac.yaml #902

**Comment by lilydjwg** [comment]
嗯，简单的 pre / post build 可以直接写 yaml。就只支持写函数名好了，其它的还是写到 lilac.py 里去？

**Comment by a-wing** [comment]
特别复杂的还是写到 lilac.py 里好。。。不过有特别复杂的吗？

**Comment by lilydjwg** [comment]
有啊，比如 vim-lily 和 rust-nightly。

**Comment by petronny** [comment]
复杂的lilac.py比如vcs包repo上游变了要删。。。
hashsum写错了得手动修改
depends, makedepends有缺的要手动加上
要是这些也能就好了

或者直接跑sh得了。。。
```yaml
build_prefix: extra-x86_64
pre_build:
  - aur_pre_build
  - sh: sed 's/hashsum1/hashsum2/' -i PKGBUILD
  - sh: [ `date +%Y%m%d` < 20181024 ] && rm -rf vcs/
  - sh: sed '/^depends=/s/)/ "git")/' -i PKGBUILD
```

**Comment by a-wing** [comment]
> depends, makedepends有缺的要手动加上

你是说 `add_depends` 和 `add_makedepends` ?

**Comment by lilydjwg** [comment]
呃，你可以直接在 lilac.py 里拿 subprocess 跑 shell 脚本的。要删旧文件的话，可以在编译机上跑 `sudo cleanup-package-files 包名` 了。

在 yaml 里写 shell 命令很容易出错的，比如你评论里写的这个 pyyaml 解析时就会报错。

**Comment by farseerfc** [comment]
現在 pre-commit 支持 lilac.yaml 了，作爲測試 yed 包只有 lilac.yaml 刪掉了 lilac.py 和 nvchecker.ini 裏的相關描述。

**Comment by farseerfc** [comment]
哦哦給 yed 加了個空的 lilac.py

**Comment by yan12125** [comment]
我參考了 https://github.com/archlinuxcn/lilac/pull/68 的格式以及百合的建議加上了maintainers。例如：

```yaml
maintainers:
  - github: yan12125
    email: username@domain.tld
```

如果有更好的表示法，歡迎提出來！

Update 2026/05/03: remove my email address here
