### ISSUE TITLE
[RFC] Add lilac.yaml unstable_skip on on_update

### ISSUE THREAD

**Issue by a-wing** [archlinuxcn/repo#991]
### 问题类型 / Type of issues

* 其它 / other

### 受影响的软件包 / Affected packages

* none
----
Default 
    unstable_skip: false

when  `unstable_skip: true`
if ver have alphabet no build

1.2.3 build
1.2.3rc, 1.2.3.bate.1, ....  No build

For example
```
update_on:
  - github: fatedier/frp
    use_latest_release: true
    unstable_skip: true
```
